#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d ○ ○ ○ ○ ○

polybar &
feh --bg-scale ~/.config/wallpapers/pg3.png &
picom &
setxkbmap -option 'grp:alt_shift_toggle' -layout us,ru &
libinput-gestures


bspc config border_width         2
bspc config window_gap          12
bspc config pointer_motion_interval 40
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
